[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"
queue = "outgoing"

[redis]
ip = "10.10.10.10"
port = 6379
password = "secret123"
database = 1

[mail]
mailfrom = "sender"
maildomain = "domain.com"
host = "10.10.10.10"
user = "user"
password = "secret123"
destination = "alvaro.castellano.vela@gmail.com"

[alarmmanager]
host = "10.10.10.10"
port = 3000

[notify]
online = true
statuschange = true
queue = true
mail = true
