[rabbitmq]
host = "localhost"
port = 5672
user = "guest"
password = "pass"
queue = "outgoing"

[redis]
ip = "10.10.10.10"
port = 6379
password = "secret123"
database = 1

[alarmmanager]
host = "10.10.10.10"
port = 3000

[notify]
online = true
statuschange = true
queue = true
mail = false
